### ISSUE TITLE
Is it possible to support progress bar for the training process?

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs-browser#15]
The FSRS-rs provided progress in `compute_parameters`:

https://github.com/open-spaced-repetition/fsrs-rs/blob/5cd2d8d965a4f20cb9bd5dc6395aa82c7445ffe8/src/training.rs#L202

Anki uses it to display progress of training:

https://github.com/ankitects/anki/blob/15506328e95ed853364759099123c94c7567d214/rslib/src/scheduler/fsrs/weights.rs#L78-L99

But I don't know whether it is possible to export the progress to js.

@asukaminato0721, @AlexErrant, @ishiko732, what do you think of it?

**Comment by ishiko732** [comment]
Sorry, I'm not very familiar with Rust. need @AlexErrant to take a look and see if it can be implemented.🥲🥲🥲

**Comment by asukaminato0721** [comment]
progress bar itself is simple

<https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress>

```html
<label for="train">Train progress:</label>

<progress id="train" max="100" value="70">70%</progress>
```

---

so the main point is get `value` for progress. Maybe need to write another `wasm_bindgen` function to get the value, then bind the `value`.

**Comment by AlexErrant** [comment]
Unfortunately, I'm not seeing any obviously good ways of implementing this. I tried/thought of a few ways:

1. [Passing a Javascript function to Rust](https://github.com/open-spaced-repetition/fsrs-browser/commit/405dfad8a71697fb9d17bf6e3ef07ba57a30ac99#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R62) as a callback to put into a `MetricsRenderer` impl. Sadly, this means [passing a _closure_, not a function pointer](https://github.com/open-spaced-repetition/fsrs-browser/commit/405dfad8a71697fb9d17bf6e3ef07ba57a30ac99#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R93-R94). This results in the following error message, which I'm unable to resolve:

```
Diagnostics:
1. `(dyn Fn(i32) + 'static)` cannot be shared between threads safely
   the trait `std::marker::Sync` is not implemented for `(dyn Fn(i32) + 'static)`
   required for `std::ptr::Unique<(dyn Fn(i32) + 'static)>` to implement `std::marker::Sync` [E0277]
2. `(dyn Fn(i32) + 'static)` cannot be sent between threads safely
   the trait `Send` is not implemented for `(dyn Fn(i32) + 'static)`
   required for `std::ptr::Unique<(dyn Fn(i32) + 'static)>` to implement `Send` [E0277]
```

I cannot pass a `js_sys::Function` directly either because it's not send/sync. Trying to [call the function in a rayon spawned thread](https://github.com/open-spaced-repetition/fsrs-browser/commit/405dfad8a71697fb9d17bf6e3ef07ba57a30ac99#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R76-R82) results in the same type of error. I then tried [making the function global by putting it in a `OnceLock`](https://github.com/open-spaced-repetition/fsrs-browser/commit/405dfad8a71697fb9d17bf6e3ef07ba57a30ac99#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R359-R360), but again that errors. I don't think anything involving `js_sys::Function` is viable - though I _really_ want it it to be. I also tried [`web_sys::MessagePort`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.MessagePort.html) but it's also not send/sync.

2. Notably [this call](https://github.com/open-spaced-repetition/fsrs-browser/commit/405dfad8a71697fb9d17bf6e3ef07ba57a30ac99#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R77) using [`extern "C"`](https://github.com/open-spaced-repetition/fsrs-browser/commit/405dfad8a71697fb9d17bf6e3ef07ba57a30ac99#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R3-R10) works. But it only works for Javascript that `fsrs-browser` defines. Ideally, it would work with _user-defined_ Javascript, since everyone will want to update their UI differently. It only works for `fsrs-browser` defined JS because of how wasm-bindgen handles [JS snippets](https://rustwasm.github.io/wasm-bindgen/reference/js-snippets.html). JS snippets are copied to the package in a hashed manner, for example `fsrs-browser/pkg/snippets/fsrs-browser-0a7bb84009d44696/js/foo.js`. This hash means there's no stable path for users to use to set any callback functions.

A workaround would be passing the function to Rust, which would then set that callback function in some JS snippet for `extern C` to use. This... feels like quite a bad hack, since JS now owns that global mutable state for storing the user's callback function.

3. Since calls to `console.log` work, [users could override the `console.log` implementation in JS](https://stackoverflow.com/questions/9216441/intercept-calls-to-console-log-in-chrome). Obviously this is a terrible solution.

I'd love to somehow make 1. work, but I'm running into the limits of my Rust skills. Are there any other things I could try? `std::sync::mpsc` also has the same limitations.

**Comment by asukaminato0721** [comment]
A naive thought, what if change console.log to setValue, since

> calls to console.log work

somethings like

```jsx
import { render } from "solid-js/web";
import { createSignal } from "solid-js";

function Counter() {
  const [count, setCount] = createSignal(0);

  setInterval(() => setCount(count() + 1), 1000); // setCount change to setProgress

  return <div>Count: {count()}</div>;
}

render(() => <Counter />, document.getElementById('app'));
```

https://www.solidjs.com/tutorial/introduction_signals?solved

**Comment by AlexErrant** [comment]
The reason `console.log` works is because it's in the global scope. Unfortunately `setCount` is not in global scope.

I ended up going with another solution that uses (abuses?) shared memory. See the above PR for details.

**Comment by asukaminato0721** [comment]
> setCount is not in global scope.

I don't know if it works.

> For example, we can build a global reactive data store by creating a signal in a global scope, and exporting it for other modules to use:

<https://www.solidjs.com/tutorial/stores_nocontext>

**Comment by AlexErrant** [comment]
Ahh, words are hard.

`console.log` is one type of "global" that's on `window` or webworker's `self`. In other words, you can call `console.log` _anywhere_. It is global _by default_.

The solid-js store you're talking about is global _once you export or import it_. That's actually a significant difference, since that export means it isn't global _until you make it global_. It is _not_ global by default.

Also, now that I think about it, I don't think option 3 would work because the override wouldn't be scoped to the web-worker. Any `console.log` overrides would only apply to the `console.log` in user-land, not in web-worker-land.

---

I made a small demo of option 2 [here](https://github.com/open-spaced-repetition/fsrs-browser/commit/f0be045dd078b564ca5e4b58269ab7d9098f7eab). Note how JS now owns that global mutable state for storing the user's callback function
