### ISSUE TITLE
[BUG?]Uncaught Error: null pointer passed to rust

### ISSUE THREAD

**Issue by ishiko732** [open-spaced-repetition/fsrs-browser#26]
After completing the training, I used `progress.free()`, but I encountered the error `Uncaught Error: null pointer passed to rust`. Even when I used `setTimeout(() => progress.free(), 1000)`, the error still occurred.

<img width="665" alt="image" src="https://github.com/open-spaced-repetition/fsrs-browser/assets/62931549/b1b4015c-5df2-47e4-8020-27e7d83b22b9">

<img width="799" alt="image" src="https://github.com/open-spaced-repetition/fsrs-browser/assets/62931549/f9d8c633-013e-49b4-b112-33b05ba30836">

Does this mean that I don't need to free the `progress` ?

**Comment by ishiko732** [comment]
I noticed that the progress `pointer` becomes `NULL` after the training has finished. 
```diff
	let progress = Progress.new()
+	console.log(progress)
	...
	self.postMessage({
		tag: 'Stop',
		parameters,
	} satisfies ProgressMessage)
+	console.log(progress)
+	// console.log(progress.pointer()) Uncaught (in promise) Error: null pointer passed to rust
```

<img width="740" alt="image" src="https://github.com/open-spaced-repetition/fsrs-browser/assets/62931549/4a1638ce-ff19-4c81-855c-974b0c70d484">

**Comment by AlexErrant** [comment]
When we create `Progress` in Javascript and pass it to `computeParameters(Anki)`, [it is _moved_](https://github.com/open-spaced-repetition/fsrs-browser/blob/b44d5ab7d0b44a7cad8b0a61a68440fdfd7e9496/src/lib.rs#L54). (Note how it is _missing_ an `&`, which indicates when an argument is _borrowed_.) Moving means that the "ownership" of the struct (object) is _moved_ to that function; in other words, it is now that function's job to clean up the argument's memory. When burn finishes training it cleans up all progress structs, which is why `progress` is null after completing training.

Honestly, this is kinda annoying as I would prefer to have a "live" reference to a struct that says "1000/1000 items processed" even _after_ training is done, but I think [`MetricsRenderer`](https://github.com/open-spaced-repetition/fsrs-rs/blob/64b5f518cff07051228461d4275f9501382a4ae3/src/training.rs#L144) needs ownership to work since it's on a different thread. So unfortunately it is possible for Javascript to hang onto a null reference even while Rust maintains its local type/memory-safety.

Please note that I am a Rust noob and all of the above could be incorrect. I know nothing and suck at everything especially Rust.

---

Side note, you _don't_ need to call `.free()` because we use [`wasm-bindgen = "0.2.92"`](https://github.com/open-spaced-repetition/fsrs-browser/blob/b44d5ab7d0b44a7cad8b0a61a68440fdfd7e9496/Cargo.toml#L23) and that version supports [weak-references](https://github.com/rustwasm/wasm-bindgen/blob/main/guide/src/reference/weak-references.md). Well, as long as you're using a browser released after 2021. [Relevant StackOverflow.](https://stackoverflow.com/questions/73655844/when-should-i-call-the-free-methods-generated-by-wasm-pack)

I'll add a comment about this to the sandbox.
