### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs-browser#3]
Did you stick into any problems?

**Comment by AlexErrant** [comment]
Still active! The next step for me is to clean up this PR and get it merged https://github.com/tracel-ai/burn/pull/938

Unfortunately, something important happened in my life that's consuming all of my free time. I plan on resuming work on the above PR in the coming weeks.

**Comment by AlexErrant** [comment]
Since the above PR was rejected, I just git-submoduled `burn` and `fsrs-rs` and made the changes I wanted. Glory to open source :)

I'm currently running into the `NotEnoughData` error when trying to run `compute_weights`, which is unsurprising. @L-M-Sherlock do you have any advice on how to minimally run this fn? I don't see any tests in `fsrs-rs` for `compute_weights`. I suppose I could just generate random data, but just wondered if you had a better solution.

**Comment by L-M-Sherlock** [comment]
We have a test in `fsrs-rs` for `compute_weights: https://github.com/open-spaced-repetition/fsrs-rs/blob/6b0207ac5b9f8ab953c494a96528e3929cc020b4/src/training.rs#L434-L489

https://github.com/open-spaced-repetition/fsrs-rs/blob/main/.github/workflows/check.sh
