### ISSUE TITLE
[Bug] unable to train

### ISSUE THREAD

**Issue by ishiko732** [open-spaced-repetition/fsrs-browser#9]
I am unable to run the training and found that this piece of code is causing the issue. 
<img width="1614" alt="image" src="https://github.com/open-spaced-repetition/fsrs-browser/assets/62931549/61600956-59e3-48a8-bc72-e60e70852055">
https://github.com/AlexErrant/burn/compare/3db5c1134fbedee58b187911786553373a82d8e4...48042af27969dfc76593b43ffcf08fcedff325b3#diff-6a35a98c03bc063fbb33e367f90ce1f477a9b10fc9508313986c7706c7558e17

```diff
- wasm-bindgen-rayon = { version = "1.0.3", optional = true, features = [
-   "no-bundler",
- ] }

+ wasm-bindgen-rayon = { version = "1.0.3", optional = true } 
```
After rolling back this code, I discovered that I can run the training normally.

<img width="1168" alt="image" src="https://github.com/open-spaced-repetition/fsrs-browser/assets/62931549/c8227deb-26bc-42a2-814f-95161e08561d">

**Comment by AlexErrant** [comment]
Oh hey my first user :)

I can replicate your error in [the sandbox](https://github.com/open-spaced-repetition/fsrs-browser/tree/main/sandbox). I enabled the `no-bundler` feature in `v0.2.2` because otherwise `vite build` failed for me, but it looks like now the problem is run-time instead of build-time. Bah.

Can you run `vite build` in your project with `v0.2.1` and `v0.2.2` and report the results? For the sandbox (and my own project), `vite build` fails in `v0.2.1` and succeeds with `v0.2.2`. However, it looks like training doesn't work with `vite build && vite preview` on `v0.2.2` for reasons that escape me.

I'm not entirely sure what the bundling story with `wasm-bindgen-rayon` and vite should be like... gonna see if I can create a minimal example.

**Comment by ishiko732** [comment]
> Can you run `vite build` in your project with `v0.2.1` and `v0.2.2` and report the results? For the sandbox (and my own project), `vite build` fails in `v0.2.1` and succeeds with `v0.2.2`. However, it looks like training doesn't work with `vite build && vite preview` on `v0.2.2` for reasons that escape me.

I tried using `fsrs-browser@0.2.1` for vite build, but it failed. However, when using `fsrs-browser@0.2.2`, the compilation was successful. However, neither of them can be used for training. (Possibly due to different compilation environments caused by npm package publishing?)
<img width="1595" alt="image" src="https://github.com/open-spaced-repetition/fsrs-browser/assets/62931549/4afe87bf-ebac-421e-bc58-8ba8aa5b68ca">
<img width="1590" alt="image" src="https://github.com/open-spaced-repetition/fsrs-browser/assets/62931549/00376fcb-ebfb-49aa-ad00-a1de441ab5a3">
<img width="1465" alt="image" src="https://github.com/open-spaced-repetition/fsrs-browser/assets/62931549/1617db5b-a33e-4f39-b2d6-d9980c3c9cce">


---

> If I use `./prod.sh` for compilation to obtain `fsrs-browser.js`, it fails to compile in both versions. However, training works with `0.2.1`, but not with `0.2.2`.
